//! Terminal User Interface for review listing and filtering.
//!
//! Provides an interactive TUI for navigating and filtering pull request
//! review comments using the bubbletea-rs Model-View-Update (MVU) pattern.

pub mod app;
pub mod components;
pub mod input;
pub mod messages;
mod reply_draft_config;
pub mod state;
mod storage;
pub mod sync;

pub use app::ReviewApp;
pub use reply_draft_config::{ReplyDraftConfig, ReplyDraftMaxLength, set_reply_draft_config};
pub use storage::{
    TimeTravelContext, set_comment_rewrite_service, set_commit_history_limit, set_git_ops_context,
    set_initial_reviews, set_initial_terminal_size, set_pr_discussion_summary_service,
    set_refresh_context, set_review_comment_verification_cache, set_telemetry_sink,
    set_time_travel_context,
};

#[cfg(feature = "test-support")]
pub use storage::get_refresh_context_for_tests;

pub(crate) use reply_draft_config::get_reply_draft_config;
pub(crate) use storage::{
    fetch_reviews, get_comment_rewrite_service, get_commit_history_limit, get_git_ops_context,
    get_initial_reviews, get_initial_terminal_size, get_pr_discussion_summary_service,
    get_refresh_locator, get_refresh_pr_title, get_review_comment_verification_cache,
    get_time_travel_context, record_sync_telemetry,
};

#[cfg(test)]
#[expect(
    clippy::ref_option_ref,
    reason = "Generated by mockall macro for Option<&T> parameters"
)]
mod tests;
