//! Unit tests for shared time-travel orchestration services.

use chrono::Utc;
use rstest::rstest;

use crate::github::models::ReviewComment;
use crate::github::models::test_support::minimal_review;
use crate::local::{
    CommitMetadata, CommitSha, CommitSnapshot, GitOperationError, GitOperations,
    LineMappingRequest, LineMappingVerification, RepoFilePath,
};

use super::{TimeTravelNavigationDirection, load_time_travel_state, navigate_time_travel_state};
use crate::time_travel::{TimeTravelInitParams, TimeTravelParams, TimeTravelState};

#[expect(
    clippy::ref_option_ref,
    reason = "Generated by mockall macro for Option<&T> parameters"
)]
mod mock_git_ops {
    use super::*;
    use mockall::mock;

    mock! {
        pub GitOps {}

        impl std::fmt::Debug for GitOps {
            fn fmt<'a>(&self, f: &mut std::fmt::Formatter<'a>) -> std::fmt::Result;
        }

        impl GitOperations for GitOps {
            fn get_commit_snapshot<'a>(
                &self,
                sha: &'a CommitSha,
                file_path: Option<&'a RepoFilePath>,
            ) -> Result<CommitSnapshot, GitOperationError>;

            fn get_file_at_commit<'a>(
                &self,
                sha: &'a CommitSha,
                file_path: &'a RepoFilePath,
            ) -> Result<String, GitOperationError>;

            fn verify_line_mapping<'a>(
                &self,
                request: &'a LineMappingRequest,
            ) -> Result<LineMappingVerification, GitOperationError>;

            fn get_parent_commits<'a>(
                &self,
                sha: &'a CommitSha,
                limit: usize,
            ) -> Result<Vec<CommitSha>, GitOperationError>;

            fn commit_exists<'a>(&self, sha: &'a CommitSha) -> bool;
        }
    }
}

use mock_git_ops::MockGitOps;

fn create_test_snapshot(sha: &str, message: &str) -> CommitSnapshot {
    let metadata = CommitMetadata::new(
        sha.to_owned(),
        message.to_owned(),
        "Test Author".to_owned(),
        Utc::now(),
    );
    CommitSnapshot::with_file_content(
        metadata,
        "src/main.rs".to_owned(),
        "fn main() {}".to_owned(),
    )
}

fn build_comment(commit_sha: &str, line_number: Option<u32>) -> ReviewComment {
    ReviewComment {
        commit_sha: Some(commit_sha.to_owned()),
        file_path: Some("src/main.rs".to_owned()),
        line_number,
        ..minimal_review(2, "Load test", "bob")
    }
}

fn build_navigation_state(index: usize) -> TimeTravelState {
    let commit_history = vec![
        CommitSha::new("abc1234567890".to_owned()),
        CommitSha::new("def5678901234".to_owned()),
        CommitSha::new("ghi9012345678".to_owned()),
    ];
    let Some(selected_sha) = commit_history.get(index).map(CommitSha::as_str) else {
        panic!("navigation state index should exist in test history");
    };
    let snapshot = create_test_snapshot(
        selected_sha,
        match index {
            0 => "Newest commit",
            1 => "Middle commit",
            _ => "Oldest commit",
        },
    );
    TimeTravelState::new(TimeTravelInitParams {
        snapshot,
        file_path: RepoFilePath::new("src/main.rs".to_owned()),
        original_line: Some(10),
        line_mapping: Some(LineMappingVerification::exact(10)),
        commit_history,
        current_index: index,
    })
}

#[test]
#[expect(
    clippy::panic_in_result_fn,
    reason = "Test returns Result to propagate setup errors via ? operator, but uses assertions for test checks"
)]
fn load_time_travel_state_success() -> Result<(), Box<dyn std::error::Error>> {
    let mut git_ops = MockGitOps::new();
    let test_snapshot = create_test_snapshot("abc1234567890", "Test commit");
    let snapshot_clone = test_snapshot.clone();

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .returning(move |_sha, _file_path| Ok(snapshot_clone.clone()));

    git_ops
        .expect_get_parent_commits()
        .times(1)
        .returning(|_sha, _limit| {
            Ok(vec![
                CommitSha::new("abc1234567890".to_owned()),
                CommitSha::new("def5678901234".to_owned()),
            ])
        });

    git_ops
        .expect_verify_line_mapping()
        .times(1)
        .returning(|request| Ok(LineMappingVerification::exact(request.line)));

    let params = TimeTravelParams::from_comment(&build_comment("abc1234567890", Some(10)))?;
    let head_sha = CommitSha::new("HEAD".to_owned());
    let state = load_time_travel_state(&git_ops, &params, Some(&head_sha), 50)?;

    assert_eq!(state.snapshot().message(), "Test commit");
    assert_eq!(state.file_path().as_str(), "src/main.rs");
    assert_eq!(state.original_line(), Some(10));
    assert_eq!(state.commit_count(), 2);

    Ok(())
}

#[test]
#[expect(
    clippy::panic_in_result_fn,
    reason = "Test returns Result to propagate setup errors via ? operator, but uses assertions for test checks"
)]
fn load_time_travel_state_passes_configured_limit() -> Result<(), Box<dyn std::error::Error>> {
    let mut git_ops = MockGitOps::new();
    let test_snapshot = create_test_snapshot("abc1234567890", "Test commit");
    let snapshot_clone = test_snapshot.clone();

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .returning(move |_sha, _file_path| Ok(snapshot_clone.clone()));

    git_ops
        .expect_get_parent_commits()
        .times(1)
        .withf(|_sha, limit| *limit == 15)
        .returning(|_sha, _limit| Ok(vec![CommitSha::new("abc1234567890".to_owned())]));

    let params = TimeTravelParams::from_comment(&build_comment("abc1234567890", None))?;
    let state = load_time_travel_state(&git_ops, &params, None, 15)?;

    assert_eq!(state.commit_count(), 1);

    Ok(())
}

#[test]
#[expect(
    clippy::panic_in_result_fn,
    reason = "Test returns Result to propagate setup errors via ? operator, but uses assertions for test checks"
)]
fn load_time_travel_state_commit_not_found() -> Result<(), Box<dyn std::error::Error>> {
    let mut git_ops = MockGitOps::new();

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .returning(|sha, _file_path| Err(GitOperationError::CommitNotFound { sha: sha.clone() }));

    let params = TimeTravelParams::from_comment(&build_comment("nonexistent", None))?;

    let result = load_time_travel_state(&git_ops, &params, None, 50);
    assert!(
        matches!(result, Err(GitOperationError::CommitNotFound { .. })),
        "expected missing commit to surface CommitNotFound, got {result:?}"
    );

    Ok(())
}

#[rstest]
fn navigate_time_travel_state_to_older_commit() {
    let mut git_ops = MockGitOps::new();
    let state = build_navigation_state(0);
    let head_sha = CommitSha::new("HEAD999".to_owned());

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .withf(|sha, file_path| sha.as_str() == "def5678901234" && file_path.is_some())
        .returning(|sha, _file_path| Ok(create_test_snapshot(sha.as_str(), "Middle commit")));

    git_ops
        .expect_verify_line_mapping()
        .times(1)
        .returning(|request| {
            Ok(LineMappingVerification::moved(
                request.line,
                request.line + 2,
            ))
        });

    let new_state = navigate_time_travel_state(
        &git_ops,
        &state,
        TimeTravelNavigationDirection::Previous,
        Some(&head_sha),
    )
    .expect("navigation should succeed")
    .expect("older navigation should return a new state");

    assert_eq!(new_state.snapshot().sha(), "def5678901234");
    assert_eq!(new_state.current_index(), 1);
}

#[rstest]
fn navigate_time_travel_state_back_to_newer_commit() {
    let mut git_ops = MockGitOps::new();
    let state = build_navigation_state(1);

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .withf(|sha, file_path| sha.as_str() == "abc1234567890" && file_path.is_some())
        .returning(|sha, _file_path| Ok(create_test_snapshot(sha.as_str(), "Newest commit")));

    let new_state =
        navigate_time_travel_state(&git_ops, &state, TimeTravelNavigationDirection::Next, None)
            .expect("navigation should succeed")
            .expect("newer navigation should return a new state");

    assert_eq!(new_state.snapshot().sha(), "abc1234567890");
    assert_eq!(new_state.current_index(), 0);
    assert!(new_state.line_mapping().is_none());
}

#[rstest]
fn navigate_time_travel_state_returns_none_at_boundary() {
    let git_ops = MockGitOps::new();
    let state = build_navigation_state(0);

    let new_state =
        navigate_time_travel_state(&git_ops, &state, TimeTravelNavigationDirection::Next, None)
            .expect("boundary navigation should not fail");

    assert!(new_state.is_none());
}

#[rstest]
fn navigate_time_travel_state_surfaces_snapshot_error() {
    let mut git_ops = MockGitOps::new();
    let state = build_navigation_state(0);

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .returning(|sha, _file_path| Err(GitOperationError::CommitNotFound { sha: sha.clone() }));

    let result = navigate_time_travel_state(
        &git_ops,
        &state,
        TimeTravelNavigationDirection::Previous,
        None,
    );

    assert!(
        matches!(result, Err(GitOperationError::CommitNotFound { .. })),
        "expected commit-not-found to surface unchanged, got {result:?}"
    );
}

#[rstest]
#[case::missing_head_sha(None)]
#[case::missing_original_line(Some(CommitSha::new("HEAD999".to_owned())))]
fn navigate_time_travel_state_skips_line_mapping_when_incomplete(
    #[case] head_sha: Option<CommitSha>,
) {
    let mut git_ops = MockGitOps::new();
    let state = if head_sha.is_some() {
        TimeTravelState::new(TimeTravelInitParams {
            snapshot: create_test_snapshot("abc1234567890", "Newest commit"),
            file_path: RepoFilePath::new("src/main.rs".to_owned()),
            original_line: None,
            line_mapping: Some(LineMappingVerification::exact(10)),
            commit_history: vec![
                CommitSha::new("abc1234567890".to_owned()),
                CommitSha::new("def5678901234".to_owned()),
                CommitSha::new("ghi9012345678".to_owned()),
            ],
            current_index: 0,
        })
    } else {
        build_navigation_state(0)
    };

    git_ops
        .expect_get_commit_snapshot()
        .times(1)
        .returning(|sha, _file_path| Ok(create_test_snapshot(sha.as_str(), "Middle commit")));

    let new_state = navigate_time_travel_state(
        &git_ops,
        &state,
        TimeTravelNavigationDirection::Previous,
        head_sha.as_ref(),
    )
    .expect("navigation should succeed")
    .expect("navigation should yield a state");

    assert!(new_state.line_mapping().is_none());
}
